name: publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install x264
        run: sudo apt-get install libx264-dev
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces
      - name: Publish crates
        run: cargo ws publish -y --from-git --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
